# Generated by Django 2.1.3 on 2018-12-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20181205_1210'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
