# Generated by Django 2.1.3 on 2018-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('role', models.TextField()),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
    ]
