# Generated by Django 2.1.3 on 2018-12-02 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
